// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// URLUpdater is an autogenerated mock type for the URLUpdater type
type URLUpdater struct {
	mock.Mock
}

// UpdateURL provides a mock function with given fields: alias, newURL
func (_m *URLUpdater) UpdateURL(alias string, newURL string) error {
	ret := _m.Called(alias, newURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(alias, newURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewURLUpdater creates a new instance of URLUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLUpdater {
	mock := &URLUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
