services:
  postgres_url:
    container_name: postgres_url
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 10s
      timeout: 4s
      retries: 5
  migrate_up:
    image: migrate/migrate
    container_name: migrate_up
    depends_on:
      postgres_url:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      ["-path", "/migrations",
      "-database",
       "postgres://${DB_USER}:${DB_PASSWORD}@postgres_url:${DB_PORT}/${DB_NAME}?sslmode=disable",
      "up"]